version: '3'
services:
  web:
    image: nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/code/:/var/www/html
  app:
    build: ./containers/php/
    depends_on:
      - db
    volumes:
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./src/code/:/var/www/html
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
    volumes:
      - ./containers/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql